from enum import Enum


class AuditAction(str, Enum):
    """Standardized audit log actions."""
    LOGIN = "LOGIN"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGOUT = "LOGOUT"
    TOKEN_REFRESH = "TOKEN_REFRESH"
    USER_CREATE = "USER_CREATE"
    USER_UPDATE = "USER_UPDATE"
    USER_DELETE = "USER_DELETE"
    ROLE_CHANGE = "ROLE_CHANGE"
    THREAT_CREATE = "THREAT_CREATE"
    THREAT_UPDATE = "THREAT_UPDATE"
    THREAT_DELETE = "THREAT_DELETE"
    ALERT_CREATE = "ALERT_CREATE"
    ALERT_UPDATE = "ALERT_UPDATE"
    ALERT_DELETE = "ALERT_DELETE"
    ALERT_ASSIGN = "ALERT_ASSIGN"
    ALERT_ESCALATE = "ALERT_ESCALATE"
    ALERT_RESOLVE = "ALERT_RESOLVE"
    INCIDENT_CREATE = "INCIDENT_CREATE"
    INCIDENT_UPDATE = "INCIDENT_UPDATE"
    INCIDENT_DELETE = "INCIDENT_DELETE"
    REPORT_CREATE = "REPORT_CREATE"
    REPORT_UPDATE = "REPORT_UPDATE"
    REPORT_DELETE = "REPORT_DELETE"
    IOC_CREATE = "IOC_CREATE"
    THREAT_INTEL_CREATE = "THREAT_INTEL_CREATE"
    SETTINGS_UPDATE = "SETTINGS_UPDATE"
    DETECTION_EXECUTE = "DETECTION_EXECUTE"


class AuditStatus(str, Enum):
    SUCCESS = "success"
    FAILURE = "failure"
