import { useEffect, useState } from "react";
import api from "../services/api";

function Reports() {
  const [reports, setReports] = useState<any[]>([]);

  useEffect(() => {
    const fetchReports = async () => {
      try {
        const response = await api.get("/reports");
        setReports(response.data || []);
      } catch (error) {
        console.error(error);
      }
    };

    fetchReports();
  }, []);

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-3xl font-semibold text-cyan-200">Reports</h2>
        <p className="mt-2 text-slate-400">Review generated intelligence and historical summaries.</p>
      </div>
      <div className="overflow-hidden rounded-3xl border border-cyber-700 bg-cyber-800 shadow-glow">
        <table className="min-w-full divide-y divide-cyber-700 text-left text-sm text-slate-200">
          <thead className="bg-cyber-900">
            <tr>
              <th className="px-6 py-4">Title</th>
              <th className="px-6 py-4">Type</th>
              <th className="px-6 py-4">Generated By</th>
              <th className="px-6 py-4">Threats</th>
              <th className="px-6 py-4">Alerts</th>
              <th className="px-6 py-4">Period</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-cyber-700 bg-cyber-800">
            {reports.map((report) => (
              <tr key={report.id} className="hover:bg-cyber-900/80">
                <td className="px-6 py-4 font-semibold text-slate-100">{report.title}</td>
                <td className="px-6 py-4 text-slate-300">{report.report_type}</td>
                <td className="px-6 py-4 text-slate-300">{report.generated_by}</td>
                <td className="px-6 py-4 text-slate-200">{report.threats_count}</td>
                <td className="px-6 py-4 text-slate-200">{report.alerts_count}</td>
                <td className="px-6 py-4 text-slate-400">{new Date(report.period_start).toLocaleDateString()} - {new Date(report.period_end).toLocaleDateString()}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default Reports;
